### ISSUE TITLE
Sponge Effect is playing in every world

### ISSUE THREAD

**Issue by Squesly** [MherZaqaryan/BedWars1058-Sponge#3]
Exmaple:

When you place sponge in arena called katsu
Its gonna play smoke Particle in every world that you have.

I think its cause from this:
![image](https://user-images.githubusercontent.com/105538755/234074287-25215d7c-a671-4406-8dc2-292a94218614.png)

You need to get players in the game Arena that player are playing.

**Comment by MherZaqaryan** [comment]
This issue is already fixed and will be available in the next update!
